export const AllPlansContent = [
  {
    planName: "Basic",
    sellingPrice: "50",
    originalPrice: "99",
    duration: "1 Month",
    descriptionEnumList: ["Unlimited Support", "24/7 Access"],
    notIncludedBenefits: ["No Free Trial"],
    popular: false,
  },
  {
    planName: "Standard",
    sellingPrice: "100",
    originalPrice: "149",
    duration: "3 Months",
    descriptionEnumList: [
      "Unlimited Support",
      "Priority Access",
      "Profile Verification",
    ],
    notIncludedBenefits: ["No Free Trial"],
    discount: "42%",
    popular: true,
  },
  {
    planName: "Premium Basic",
    sellingPrice: "200",
    originalPrice: "399",
    duration: "6 Months",
    descriptionEnumList: [
      "Unlimited Support",
      "Priority Access",
      "Profile Verification",
      "Access to Premium Features",
    ],
    notIncludedBenefits: ["No Free Trial"],
    discount: "59%",
    popular: true,
  },
  {
    planName: "Premium Plus",
    sellingPrice: "500",
    originalPrice: "699",
    duration: "6 Months",
    descriptionEnumList: [
      "Unlimited Support",
      "Priority Access",
      "Profile Verification",
      "Access to Premium Features",
    ],
    notIncludedBenefits: ["No Free Trial"],
    discount: "59%",
    popular: true,
  },
  {
    planName: "Premium Deluxe",
    sellingPrice: "1000",
    originalPrice: "1199",
    duration: "6 Months",
    descriptionEnumList: [
      "Unlimited Support",
      "Priority Access",
      "Profile Verification",
      "Access to Premium Features",
    ],
    notIncludedBenefits: ["No Free Trial"],
    discount: "59%",
    popular: true,
  },
];
