// Authentication Routes
export const AuthRoutes = {
  LOGIN: "/login",
  ADMIN_LOGIN: "/admin/gateway/secure/9f3a7c-admin/auth",
  REGISTER: "/register",
  CHANGE_PASSSORD: "/forget-password",
  MAINTENANCE: "/maintenance",
};

// Authenticated Routes
export const AuthenticatedRoutes = {
  USER_HOME: "/",
  USER_DASHBOARD: "/dashboard",
  USER_PROFILE: "/profile",
  BANK_DETAILS: "/bank-details",
  PACKAGE_REPORT: "/package-report",
  REFERRAL_INCOME_REPORT: "/referral-income-report",
  DEPOSIT_USDT: "/deposit-usdt",
  NEWS_AND_NOTIF: "/news-and-notif",
  SPIN_INCOME_REPORT: "/spin-income-report",
  LEVEL_INCOME_REPORT: "/trade-level-Income-history",
  SERVICE_LEVEL_INCOME_REPORT: "/service-level-income-history",
  MATCHING_INCOME_REPORT: "/matching-income-report",
  ROI_INCOME_HISTORY: "/roi-history",
  ROYALTY_INCOME_REPORT: "/royalty-income-report",
  FUND_TRANSFER: "/fund-transfer",
  FUND_REQUEST: "/fund-request",
  FUND_REQUEST_HISTORY: "/fund-request-history",
  FUND_TRANSFER_HISTORY: "/fund-transfer-history",
  TEAM_DIRECT: "/team-direct",
  TEAM_TREE: "/team-tree",
  WALLET: "/wallet",
  WITHDRAWAL_REPORT: "/withdrawal-report",
  ADMIN_DASHBOARD: "/admin-dashboard",
  PENDING_USERS: "/pending-users",
  PENDING_FUND_REQUEST: "/pending-fund-request",

  APPROVED_USERS: "/approved-users",
  APPROVED_FUND_REQUEST: "/approved-fund-request",
  APPROVED_WITHDRAWAL_REQUEST: "/approved-withdrawal-request",
  REJECTED_USERS: "/rejected-users",
  REJECTED_FUND_REQUEST: "/rejected-fund-request",
  REJECTED_WITHDRAWAL_REQUEST: "/rejected-withdrawal-request",
  SUPPORT_RAISE_TICKET_HISTORY: "/support-raise-ticket-history",
  SUPPORT_RAISE_TICKET: "/support-raise-ticket",
  RAISE_TICKET_LIST: "/raise-ticket-list",
  ALL_USERS: "/all-users",
  PURCHASE_PLAN_HISTORY: "/purchase-plan-history",
  ROI_INCOME_REPORT: "/trading-profit-report",
  NEWS_AND_NOTIF_ADMIN: "/news-and-notif-admin",
  ACTIVE_USERS: "/active-users",
  MIN_MAX_LIMIT: "/min-max-limit",
  MIN_PACKAGE_AMOUNT: "/min-package-amount",
  WITHDRAWAL_BLOCK: "/withdrawal-block",

  // ===================> Botx Routes of user Pnnel bro  <= ===================//

  PROFILE: "/user-profile",
  SERVICE_PACKAGES: "/service-package",
  MINING_PACKAGES: "/mining-package",
  MAKE_INVESTMENT: "/make-investement",
  INVESTMENT_HISTORY: "/investment-history",
  DIRECT_TEAM: "/direct-team",
  ALL_TEAM: "/all-team",
  CLUB_INCOME: "/club-income",
  MATCHING_INCOME: "/matching-income",
  SERVICE_GENRATION: "/service-genration",
  DEPOSIT_FUND: "/deposit-fund",
  DEPOSIT_FUND_INVOICE: "/deposit-fund-invoice",
  RANK_AND_REWARD: "/rank-and-reward",
  TRANSFER_FUND: "/transfer-fund",
  TRANSFER_FUND_REPORT: "/transfer-fund-report",
  FUND_RECIVE: "/fund-recive",
  WITHDRAW_FUND_BOT: "/withdraw-fund",
  WITHDRAW_FUND_REPORT: "/withdraw-fund-report",
  INCOME_SUMMARY: "/income-summary",
  SERVICE_PACKAGE_HISTORY: "/service-package-buyer-history",
  TOPUP_USERS: "/topup-users",
  MATCHING_INCOME_REPORT_BOTX: "/matching-income-report",
  LEVEL_INCOME_REPORT_BOTX: "/level-income-report",
  RANK_REWARD: "/rank-reward-report",
  CLUB_INCOME_HISTORY: "/get-club-income-history",
  EIDT_PROFILE_ADMIN: "/edit-profile-admin",
  NESTED_TEAM: "/nested-team",
  TOPUP_PACKAGE_WALLET: "/add-fund-package-wallet",
  TOPUP_PACKAGE_WALLET_HISTORY: "/topup-package-wallet-history",
  SWAP: "/swap",
  SWAP_HISTORY: "/swap-history",
  SERVICE_PACKAGE_ACTIVATION_HISTORY: "/service-package-activation-history",

  // ===================>

  ACTIVATE_BOT: "/trade-bot",
  TRADING_LEVEL_INCOME: "/service-level-income",
  REWARD_INCOME: "/reward-income",
  IB_INCOME: "/ib-income",
  TOPUP_MAIN_WALLET: "/principle-withdraw-report",
  ACTIVATE_USER_ID: "/activate-user-id",
  INVESTMENT_INVOICE: "/investment-invoice",
  BUSINESS_PLAN_HISTORY: "/business-plan-history",
  DEDUCT_FUND_HISTORY_BY_ADMIN: "/fund-deduct-history",
  MONTHLY_CLOSING_REPORT: "/monthly-closing-report",

  // ================admin=========>
  PENDING_WITHDRAWAL_REQUEST: "/pending-withdrawal-request",
  BOT_SETTINGS: "/bot-settings",
  BULK_REGISTER: "/bulk-register",
  TRANSACTION_PASS: "/setup-transaction-password",
  FAST_TRACK_INCOME: "/fast-track-income",
  ACTIVATE_SERVICE_PACKAGE: "/activate-serive-package",
  ADD_INVESTMENT: "/add-investment",
  ADMIN_IB_INCOME_HISTORY: "/ib-income-history",
  ADMIN_FAST_TRACK_HISTORY: "/fast-track-history",
  ALL_TEAM_NETWORK: "/all-team-network",
  PERSENTATION: "/persentation",
  // FORGOT_PASSWORD:"/forgot-password"
  ADD_MATCHING: "/add-matching",
  CUSTOM_ROI: "/roi-settings",
  PIN_ID: "/pin-id",
  DEDUCT_FUND: "/deduct-fund",
  ADMIN_DEDUCT_FUND_HISTORY: "/admin-deduct-fund-history",
  PRINCIPLE_WITHDRAW_REPORT: "/principle-withdraw-report",
  ADD_INVESTMENT_HISTORY: "/add-investment-history",
  OTHER_SERVICE_PACKAGE_ACTIVATION_HISTORY:
    "/service-package-activation-history-other",
  PORTFOLIO: "/portfolio",
  ADD_BOT_BUSINESS: "/add-bot-business",
  ADD_FUND_BUSINESS: "/add-fund-business",
  MAINTENANCE_MODE: "/maintenance-mode",
  DEDUCT_INVESTMENT: "/deduct-investment",
  PIN_USER_HISTORY: "/pin-user-history",
  USER_PIN_ID_HISTORY: "/user-pin-id-history",
};
